import type { Company } from "./types";
import type { LocalizedName } from "./types";

const CN_CITIES = {
  beijing: { en: "Beijing", zh: "北京" },
  shanghai: { en: "Shanghai", zh: "上海" },
  shenzhen: { en: "Shenzhen", zh: "深圳" },
  guangzhou: { en: "Guangzhou", zh: "广州" },
  chengdu: { en: "Chengdu", zh: "成都" },
  suzhou: { en: "Suzhou", zh: "苏州" },
  xian: { en: "Xian", zh: "西安" },
  wuxi: { en: "Wuxi", zh: "无锡" },
  hangzhou: { en: "Hangzhou", zh: "杭州" },
  nanjing: { en: "Nanjing", zh: "南京" },
  wuhan: { en: "Wuhan", zh: "武汉" },
  hefei: { en: "Hefei", zh: "合肥" },
  xiamen: { en: "Xiamen", zh: "厦门" },
  dalian: { en: "Dalian", zh: "大连" },
  hongkong: { en: "Hong Kong", zh: "香港" },
} as const satisfies Record<string, LocalizedName>;

const C = CN_CITIES;

export const CN_COMPANIES: Company[] = [
  {
    id: "apple-cn",
    name: {
      en: "Apple",
      zh: "苹果",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "amazon-cn",
    name: {
      en: "Amazon",
      zh: "亚马逊",
    },
    region: "CN",
    cities: [C.beijing, C.guangzhou, C.shanghai, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 18,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "intel-cn",
    name: {
      en: "Intel",
      zh: "英特尔",
    },
    region: "CN",
    cities: [C.beijing, C.chengdu, C.shanghai, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "oracle-cn",
    name: {
      en: "Oracle",
      zh: "甲骨文",
    },
    region: "CN",
    cities: [C.beijing, C.chengdu, C.guangzhou, C.shanghai, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 18,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "morgan-stanley-cn",
    name: {
      en: "Morgan Stanley",
      zh: "摩根士丹利",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "microsoft-cn",
    name: {
      en: "Microsoft",
      zh: "微软",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.suzhou],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "zalando-cn",
    name: {
      en: "Zalando",
      zh: "嘉兰朵",
    },
    region: "CN",
    cities: [C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 12,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "flexport-cn",
    name: {
      en: "Flexport",
      zh: "飞协博",
    },
    region: "CN",
    cities: [C.shanghai, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 12,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "qualcomm-cn",
    name: {
      en: "Qualcomm",
      zh: "高通",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.xian, C.wuxi],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 12,
    },
  },
  {
    id: "siemens-cn",
    name: {
      en: "Siemens",
      zh: "西门子",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "philips-cn",
    name: {
      en: "Philips",
      zh: "飞利浦",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "schneider-cn",
    name: {
      en: "Schneider",
      zh: "施耐德",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "afterpay-cn",
    name: {
      en: "Afterpay",
      zh: "Afterpay",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "airbnb-cn",
    name: {
      en: "Airbnb",
      zh: "爱彼迎",
    },
    region: "CN",
    cities: [C.beijing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "amd-cn",
    name: {
      en: "AMD",
      zh: "超微半导体",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "arcsoft-cn",
    name: {
      en: "ArcSoft",
      zh: "虹软",
    },
    region: "CN",
    cities: [C.hangzhou],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "arm-cn",
    name: {
      en: "ARM",
      zh: "安谋",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "autodesk-cn",
    name: {
      en: "Autodesk",
      zh: "欧特克",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "booking-cn",
    name: {
      en: "Booking",
      zh: "缤客",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "bosch-cn",
    name: {
      en: "Bosch Group",
      zh: "博世",
    },
    region: "CN",
    cities: [C.shanghai, C.suzhou, C.wuxi],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "calix-cn",
    name: {
      en: "Calix",
      zh: "Calix",
    },
    region: "CN",
    cities: [C.nanjing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "canva-cn",
    name: {
      en: "Canva",
      zh: "Canva",
    },
    region: "CN",
    cities: [C.beijing, C.wuhan],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "cisco-cn",
    name: {
      en: "Cisco",
      zh: "思科",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.hangzhou, C.suzhou],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "citrix-cn",
    name: {
      en: "Citrix",
      zh: "思杰",
    },
    region: "CN",
    cities: [C.nanjing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "continental-cn",
    name: {
      en: "Continental AG",
      zh: "大陆集团",
    },
    region: "CN",
    cities: [C.shanghai, C.hefei],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "coolapk-cn",
    name: {
      en: "Coolapk",
      zh: "酷安",
    },
    region: "CN",
    cities: [C.beijing, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "coupang-cn",
    name: {
      en: "Coupang",
      zh: "酷澎",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "cstc-cn",
    name: {
      en: "CSTC",
      zh: "花旗金融",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "dell-cn",
    name: {
      en: "Dell",
      zh: "戴尔",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "douban-cn",
    name: {
      en: "Douban",
      zh: "豆瓣",
    },
    region: "CN",
    cities: [C.beijing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "duolingo-cn",
    name: {
      en: "Duolingo",
      zh: "多邻国",
    },
    region: "CN",
    cities: [C.beijing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ebay-cn",
    name: {
      en: "eBay",
      zh: "eBay",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ehealth-cn",
    name: {
      en: "eHealth",
      zh: "eHealth",
    },
    region: "CN",
    cities: [C.xiamen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ea-cn",
    name: {
      en: "Electronic Arts",
      zh: "EA",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "emc-cn",
    name: {
      en: "EMC",
      zh: "EMC",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "epam-cn",
    name: {
      en: "EPAM Systems",
      zh: "EPAM",
    },
    region: "CN",
    cities: [C.shanghai, C.shenzhen, C.suzhou, C.chengdu],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ericsson-cn",
    name: {
      en: "Ericsson",
      zh: "爱立信",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "freewheel-cn",
    name: {
      en: "FreeWheel",
      zh: "FreeWheel",
    },
    region: "CN",
    cities: [C.beijing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ge-cn",
    name: {
      en: "GE",
      zh: "通用电气",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "google-cn",
    name: {
      en: "Google",
      zh: "谷歌",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "grab-cn",
    name: {
      en: "Grab",
      zh: "Grab",
    },
    region: "CN",
    cities: [C.beijing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "honeywell-cn",
    name: {
      en: "Honeywell",
      zh: "霍尼韦尔",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "hp-cn",
    name: {
      en: "HP",
      zh: "惠普",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "hsbc-cn",
    name: {
      en: "HSBC",
      zh: "汇丰银行",
    },
    region: "CN",
    cities: [C.shanghai, C.guangzhou, C.xian],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "hulu-cn",
    name: {
      en: "Hulu",
      zh: "Hulu",
    },
    region: "CN",
    cities: [C.beijing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ibm-cn",
    name: {
      en: "IBM",
      zh: "IBM",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "iherb-cn",
    name: {
      en: "iHerb",
      zh: "iHerb",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "jetbrains-cn",
    name: {
      en: "JetBrains",
      zh: "JetBrains",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "kong-cn",
    name: {
      en: "Kong",
      zh: "Kong",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "leetcode-cn",
    name: {
      en: "LeetCode",
      zh: "LeetCode",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "lego-cn",
    name: {
      en: "LEGO Group",
      zh: "乐高",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "linkedin-cn",
    name: {
      en: "LinkedIn",
      zh: "领英",
    },
    region: "CN",
    cities: [C.beijing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "microfocus-cn",
    name: {
      en: "Micro Focus",
      zh: "Micro Focus",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "microstrategy-cn",
    name: {
      en: "MicroStrategy",
      zh: "MicroStrategy",
    },
    region: "CN",
    cities: [C.hangzhou],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ni-cn",
    name: {
      en: "National Instruments",
      zh: "NI",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "nike-cn",
    name: {
      en: "Nike",
      zh: "耐克",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "nokia-cn",
    name: {
      en: "Nokia",
      zh: "诺基亚",
    },
    region: "CN",
    cities: [C.shanghai, C.nanjing, C.hangzhou],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "nomura-cn",
    name: {
      en: "Nomura",
      zh: "野村证券",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "nvidia-cn",
    name: {
      en: "NVIDIA",
      zh: "英伟达",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "optiver-cn",
    name: {
      en: "Optiver",
      zh: "Optiver",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "paypal-cn",
    name: {
      en: "PayPal",
      zh: "PayPal",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "pivotal-cn",
    name: {
      en: "Pivotal",
      zh: "Pivotal",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "rakuten-cn",
    name: {
      en: "Rakuten",
      zh: "乐天",
    },
    region: "CN",
    cities: [C.shanghai, C.dalian],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "redhat-cn",
    name: {
      en: "Red Hat",
      zh: "红帽",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.xian],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ringcentral-cn",
    name: {
      en: "RingCentral",
      zh: "RingCentral",
    },
    region: "CN",
    cities: [C.xiamen, C.hangzhou, C.hongkong],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "rippling-cn",
    name: {
      en: "Rippling",
      zh: "Rippling",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sandisk-cn",
    name: {
      en: "SanDisk",
      zh: "闪迪",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sap-cn",
    name: {
      en: "SAP",
      zh: "思爱普",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 30,
      annualPaidSickLeaveDays: 25,
    },
  },
  {
    id: "smartnews-cn",
    name: {
      en: "SmartNews",
      zh: "SmartNews",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "snap-cn",
    name: {
      en: "Snap",
      zh: "Snap",
    },
    region: "CN",
    cities: [C.beijing, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "starbucks-cn",
    name: {
      en: "Starbucks",
      zh: "星巴克",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "statestreet-cn",
    name: {
      en: "State Street",
      zh: "道富银行",
    },
    region: "CN",
    cities: [C.hangzhou],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "suse-cn",
    name: {
      en: "SUSE",
      zh: "SUSE",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.xian],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "tradedesk-cn",
    name: {
      en: "The Trade Desk",
      zh: "The Trade Desk",
    },
    region: "CN",
    cities: [C.shanghai, C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "thoughtworks-cn",
    name: {
      en: "ThoughtWorks",
      zh: "ThoughtWorks",
    },
    region: "CN",
    cities: [C.xian, C.beijing, C.shenzhen, C.chengdu, C.wuhan, C.shanghai, C.hongkong],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "trendmicro-cn",
    name: {
      en: "Trend Micro",
      zh: "趋势科技",
    },
    region: "CN",
    cities: [C.nanjing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "tubi-cn",
    name: {
      en: "Tubi",
      zh: "Tubi",
    },
    region: "CN",
    cities: [C.beijing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "tusimple-cn",
    name: {
      en: "TuSimple",
      zh: "图森未来",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "twosigma-cn",
    name: {
      en: "Two Sigma",
      zh: "Two Sigma",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ubisoft-cn",
    name: {
      en: "Ubisoft",
      zh: "育碧",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "unity-cn",
    name: {
      en: "Unity",
      zh: "Unity",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "vipshop-cn",
    name: {
      en: "Vipshop",
      zh: "唯品会",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "vmware-cn",
    name: {
      en: "VMware",
      zh: "VMware",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "wework-cn",
    name: {
      en: "WeWork",
      zh: "WeWork",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "wish-cn",
    name: {
      en: "Wish",
      zh: "Wish",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "worksapps-cn",
    name: {
      en: "Works Applications",
      zh: "Works Applications",
    },
    region: "CN",
    cities: [C.shanghai],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "xmind-cn",
    name: {
      en: "XMind",
      zh: "XMind",
    },
    region: "CN",
    cities: [C.shenzhen],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "zhihu-cn",
    name: {
      en: "Zhihu",
      zh: "知乎",
    },
    region: "CN",
    cities: [C.beijing],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "zoom-cn",
    name: {
      en: "Zoom",
      zh: "Zoom",
    },
    region: "CN",
    cities: [C.hefei, C.hangzhou, C.suzhou],
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 0.5,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
];
