import type { Company } from "./types";
import type { LocalizedName } from "./types";

const CN_CITIES = {
  beijing: { en: "Beijing", zh: "北京" },
  shanghai: { en: "Shanghai", zh: "上海" },
  shenzhen: { en: "Shenzhen", zh: "深圳" },
  guangzhou: { en: "Guangzhou", zh: "广州" },
  chengdu: { en: "Chengdu", zh: "成都" },
  suzhou: { en: "Suzhou", zh: "苏州" },
  xian: { en: "Xian", zh: "西安" },
  wuxi: { en: "Wuxi", zh: "无锡" },
  hangzhou: { en: "Hangzhou", zh: "杭州" },
  nanjing: { en: "Nanjing", zh: "南京" },
  wuhan: { en: "Wuhan", zh: "武汉" },
  hefei: { en: "Hefei", zh: "合肥" },
  xiamen: { en: "Xiamen", zh: "厦门" },
  dalian: { en: "Dalian", zh: "大连" },
  hongkong: { en: "Hong Kong", zh: "香港" },
  remote: { en: "Remote", zh: "远程" },
} as const satisfies Record<string, LocalizedName>;

const C = CN_CITIES;

export const CN_COMPANIES: Company[] = [
  {
    id: "apple-cn",
    name: {
      en: "Apple",
      zh: "Apple/苹果",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.suzhou, C.chengdu, C.remote],
    website: "https://jobs.apple.com/zh-cn/search?location=china-CHNC",
    linkedin: "apple",
    discussion: 2,
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 12,
    },
  },
  {
    id: "amazon-cn",
    name: {
      en: "Amazon",
      zh: "Amazon/亚马逊",
    },
    region: "CN",
    cities: [C.shanghai, C.shenzhen, C.beijing, C.chengdu, C.dalian],
    website: "https://www.amazon.jobs/en/search?country[]=CHN",
    linkedin: "amazon",
    discussion: 3,
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 12,
    },
  },
  {
    id: "intel-cn",
    name: {
      en: "Intel",
      zh: "英特尔",
    },
    region: "CN",
    cities: [C.beijing, C.chengdu, C.shanghai, C.xiamen],
    website:
      "https://jobs.intel.cn/intel/position/index?recruitmentType=SOCIALRECRUITMENT&keyword=&baseProvinceCity=",
    linkedin: "intel",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "oracle-cn",
    name: {
      en: "Oracle",
      zh: "甲骨文",
    },
    region: "CN",
    cities: [C.beijing, C.chengdu, C.guangzhou, C.shanghai, C.shenzhen],
    website: "https://www.oracle.com",
    linkedin: "oracle",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 18,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "morgan-stanley-cn",
    name: {
      en: "Morgan Stanley",
      zh: "摩根士丹利",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.morganstanley.com",
    linkedin: "morgan-stanley",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "microsoft-cn",
    name: {
      en: "Microsoft",
      zh: "微软",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.suzhou],
    website: "https://www.microsoft.com",
    linkedin: "microsoft",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "zalando-cn",
    name: {
      en: "Zalando",
      zh: "Zalando/嘉兰朵",
    },
    region: "CN",
    cities: [C.shenzhen],
    website: "https://www.zalando.com",
    linkedin: "zalando",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 12,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "flexport-cn",
    name: {
      en: "Flexport",
      zh: "Flexport/飞协博",
    },
    region: "CN",
    cities: [C.shanghai, C.shenzhen],
    website: "https://www.flexport.com",
    linkedin: "flexport",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 12,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "qualcomm-cn",
    name: {
      en: "Qualcomm",
      zh: "高通",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.xian, C.wuxi],
    website: "https://www.qualcomm.com",
    linkedin: "qualcomm",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 12,
    },
  },
  {
    id: "siemens-cn",
    name: {
      en: "Siemens",
      zh: "西门子",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen],
    website: "https://www.siemens.com",
    linkedin: "siemens",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "philips-cn",
    name: {
      en: "Philips",
      zh: "飞利浦",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen],
    website: "https://www.philips.com",
    linkedin: "philips",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "schneider-electric-cn",
    name: {
      en: "Schneider Electric",
      zh: "施耐德电气",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen],
    website: "https://www.schneiderelectric.com",
    linkedin: "schneider-electric",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "afterpay-cn",
    name: {
      en: "Afterpay",
      zh: "Afterpay",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.afterpay.com",
    linkedin: "afterpay",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "airbnb-cn",
    name: {
      en: "Airbnb",
      zh: "Airbnb/爱彼迎",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://careers.airbnb.com",
    linkedin: "airbnb",
    discussion: 4,
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 12,
    },
  },
  {
    id: "amd-cn",
    name: {
      en: "AMD",
      zh: "AMD/超微半导体",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.amd.com",
    linkedin: "amd",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "arcsoft-cn",
    name: {
      en: "ArcSoft",
      zh: "虹软",
    },
    region: "CN",
    cities: [C.hangzhou],
    website: "https://www.arcsoft.com",
    linkedin: "arcsoft",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "arm-cn",
    name: {
      en: "ARM",
      zh: "ARM/安谋",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.arm.com",
    linkedin: "arm",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "autodesk-cn",
    name: {
      en: "Autodesk",
      zh: "Autodesk/欧特克",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.autodesk.com",
    linkedin: "autodesk",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "booking-cn",
    name: {
      en: "Booking",
      zh: "Booking/缤客",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.booking.com",
    linkedin: "booking",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "bosch-cn",
    name: {
      en: "Bosch Group",
      zh: "博世",
    },
    region: "CN",
    cities: [C.shanghai, C.suzhou, C.wuxi],
    website: "https://www.boschgroup.com",
    linkedin: "bosch-group",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "calix-cn",
    name: {
      en: "Calix",
      zh: "Calix",
    },
    region: "CN",
    cities: [C.nanjing],
    website: "https://www.calix.com",
    linkedin: "calix",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "canva-cn",
    name: {
      en: "Canva",
      zh: "Canva/可画",
    },
    region: "CN",
    cities: [C.beijing, C.wuhan],
    website: "https://www.canva.com",
    linkedin: "canva",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "cisco-cn",
    name: {
      en: "Cisco",
      zh: "思科",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.hangzhou, C.suzhou, C.shenzhen],
    website: "https://www.cisco.com",
    linkedin: "cisco",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "citrix-cn",
    name: {
      en: "Citrix",
      zh: "思杰",
    },
    region: "CN",
    cities: [C.nanjing],
    website: "https://www.citrix.com",
    linkedin: "citrix",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "continental-cn",
    name: {
      en: "Continental AG",
      zh: "大陆集团",
    },
    region: "CN",
    cities: [C.shanghai, C.hefei],
    website: "https://www.continentalag.com",
    linkedin: "continental-ag",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "coolapk-cn",
    name: {
      en: "Coolapk",
      zh: "酷安",
    },
    region: "CN",
    cities: [C.beijing, C.shenzhen],
    website: "https://www.coolapk.com",
    linkedin: "coolapk",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "coupang-cn",
    name: {
      en: "Coupang",
      zh: "酷澎",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.coupang.com",
    linkedin: "coupang",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "cstc-cn",
    name: {
      en: "CSTC",
      zh: "花旗金融",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.cstc.com",
    linkedin: "cstc",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "dell-cn",
    name: {
      en: "Dell",
      zh: "戴尔",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.dell.com",
    linkedin: "dell",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "douban-cn",
    name: {
      en: "Douban",
      zh: "豆瓣",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.douban.com",
    linkedin: "douban",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "duolingo-cn",
    name: {
      en: "Duolingo",
      zh: "多邻国",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.duolingo.com",
    linkedin: "duolingo",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ebay-cn",
    name: {
      en: "eBay",
      zh: "eBay",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.ebay.com",
    linkedin: "ebay",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ehealth-cn",
    name: {
      en: "eHealth",
      zh: "eHealth",
    },
    region: "CN",
    cities: [C.xiamen],
    website: "https://www.ehealth.com",
    linkedin: "ehealth",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ea-cn",
    name: {
      en: "Electronic Arts",
      zh: "EA",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.electronicarts.com",
    linkedin: "electronic-arts",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "emc-cn",
    name: {
      en: "EMC",
      zh: "EMC",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.emc.com",
    linkedin: "emc",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "epam-cn",
    name: {
      en: "EPAM Systems",
      zh: "EPAM/亿磐",
    },
    region: "CN",
    cities: [C.shanghai, C.shenzhen, C.suzhou, C.chengdu],
    website: "https://www.epamsystems.com",
    linkedin: "epam-systems",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ericsson-cn",
    name: {
      en: "Ericsson",
      zh: "爱立信",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.ericsson.com",
    linkedin: "ericsson",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "freewheel-cn",
    name: {
      en: "FreeWheel",
      zh: "FreeWheel",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.freewheel.com",
    linkedin: "freewheel",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ge-cn",
    name: {
      en: "GE",
      zh: "通用电气",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.ge.com",
    linkedin: "ge",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "google-cn",
    name: {
      en: "Google",
      zh: "谷歌",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.google.com",
    linkedin: "google",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "grab-cn",
    name: {
      en: "Grab",
      zh: "Grab",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.grab.com",
    linkedin: "grab",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "honeywell-cn",
    name: {
      en: "Honeywell",
      zh: "霍尼韦尔",
    },
    region: "CN",
    cities: [C.shanghai, C.guangzhou],
    website: "https://www.honeywell.com",
    linkedin: "honeywell",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "hp-cn",
    name: {
      en: "HP",
      zh: "惠普",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.hp.com",
    linkedin: "hp",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "hsbc-cn",
    name: {
      en: "HSBC",
      zh: "汇丰银行",
    },
    region: "CN",
    cities: [C.shanghai, C.guangzhou, C.xian],
    website: "https://www.hsbc.com",
    linkedin: "hsbc",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "hulu-cn",
    name: {
      en: "Hulu",
      zh: "Hulu",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.hulu.com",
    linkedin: "hulu",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ibm-cn",
    name: {
      en: "IBM",
      zh: "IBM",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.ibm.com",
    linkedin: "ibm",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "iherb-cn",
    name: {
      en: "iHerb",
      zh: "iHerb",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.iherb.com",
    linkedin: "iherb",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "jetbrains-cn",
    name: {
      en: "JetBrains",
      zh: "JetBrains",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.jetbrains.com",
    linkedin: "jetbrains",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "kong-cn",
    name: {
      en: "Kong",
      zh: "Kong",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.kong.com",
    linkedin: "kong",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "leetcode-cn",
    name: {
      en: "LeetCode",
      zh: "LeetCode",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.leetcode.com",
    linkedin: "leetcode",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "lego-cn",
    name: {
      en: "LEGO Group",
      zh: "乐高",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.legogroup.com",
    linkedin: "lego-group",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "linkedin-cn",
    name: {
      en: "LinkedIn",
      zh: "领英",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.linkedin.com",
    linkedin: "linkedin",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "microfocus-cn",
    name: {
      en: "Micro Focus",
      zh: "Micro Focus",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.microfocus.com",
    linkedin: "micro-focus",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "microstrategy-cn",
    name: {
      en: "MicroStrategy",
      zh: "MicroStrategy",
    },
    region: "CN",
    cities: [C.hangzhou],
    website: "https://www.microstrategy.com",
    linkedin: "microstrategy",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ni-cn",
    name: {
      en: "National Instruments",
      zh: "NI",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.nationalinstruments.com",
    linkedin: "national-instruments",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "nike-cn",
    name: {
      en: "Nike",
      zh: "耐克",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.nike.com",
    linkedin: "nike",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "nokia-cn",
    name: {
      en: "Nokia",
      zh: "诺基亚",
    },
    region: "CN",
    cities: [C.shanghai, C.nanjing, C.hangzhou],
    website: "https://www.nokia.com",
    linkedin: "nokia",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "nvidia-cn",
    name: {
      en: "NVIDIA",
      zh: "英伟达",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.chengdu, C.hangzhou, C.hongkong],
    website: "https://www.nvidia.com",
    linkedin: "nvidia",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "optiver-cn",
    name: {
      en: "Optiver",
      zh: "Optiver",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.optiver.com",
    linkedin: "optiver",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "paypal-cn",
    name: {
      en: "PayPal",
      zh: "PayPal/贝宝",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.paypal.com",
    linkedin: "paypal",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "pivotal-cn",
    name: {
      en: "Pivotal",
      zh: "Pivotal",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.pivotal.com",
    linkedin: "pivotal",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "rakuten-cn",
    name: {
      en: "Rakuten",
      zh: "乐天",
    },
    region: "CN",
    cities: [C.shanghai, C.dalian],
    website: "https://www.rakuten.com",
    linkedin: "rakuten",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "redhat-cn",
    name: {
      en: "RedHat",
      zh: "RedHat/红帽",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.xian],
    website: "https://www.redhat.com",
    linkedin: "red-hat",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ringcentral-cn",
    name: {
      en: "RingCentral",
      zh: "RingCentral",
    },
    region: "CN",
    cities: [C.xiamen, C.hangzhou, C.hongkong],
    website: "https://www.ringcentral.com",
    linkedin: "ringcentral",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "rippling-cn",
    name: {
      en: "Rippling",
      zh: "Rippling",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.rippling.com",
    linkedin: "rippling",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sandisk-cn",
    name: {
      en: "SanDisk",
      zh: "闪迪",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.sandisk.com",
    linkedin: "sandisk",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sap-cn",
    name: {
      en: "SAP",
      zh: "SAP/思爱普",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.sap.com",
    linkedin: "sap",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 30,
      annualPaidSickLeaveDays: 25,
    },
  },
  {
    id: "smartnews-cn",
    name: {
      en: "SmartNews",
      zh: "SmartNews",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.smartnews.com",
    linkedin: "smartnews",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "snap-cn",
    name: {
      en: "Snap",
      zh: "Snap",
    },
    region: "CN",
    cities: [C.beijing, C.shenzhen],
    website: "https://www.snap.com",
    linkedin: "snap",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "starbucks-cn",
    name: {
      en: "Starbucks",
      zh: "星巴克",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.starbucks.com",
    linkedin: "starbucks",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "statestreet-cn",
    name: {
      en: "State Street",
      zh: "道富银行",
    },
    region: "CN",
    cities: [C.hangzhou],
    website: "https://www.statestreet.com",
    linkedin: "state-street",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "suse-cn",
    name: {
      en: "SUSE",
      zh: "SUSE",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.xian],
    website: "https://www.suse.com",
    linkedin: "suse",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "tradedesk-cn",
    name: {
      en: "The Trade Desk",
      zh: "The Trade Desk",
    },
    region: "CN",
    cities: [C.shanghai, C.shenzhen],
    website: "https://www.thetradedesk.com",
    linkedin: "the-trade-desk",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "thoughtworks-cn",
    name: {
      en: "ThoughtWorks",
      zh: "ThoughtWorks",
    },
    region: "CN",
    cities: [C.xian, C.beijing, C.shenzhen, C.chengdu, C.wuhan, C.shanghai, C.hongkong],
    website: "https://www.thoughtworks.com",
    linkedin: "thoughtworks",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "trendmicro-cn",
    name: {
      en: "Trend Micro",
      zh: "趋势科技",
    },
    region: "CN",
    cities: [C.nanjing],
    website: "https://www.trendmicro.com",
    linkedin: "trend-micro",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "tubi-cn",
    name: {
      en: "Tubi",
      zh: "Tubi",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.tubi.com",
    linkedin: "tubi",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "tusimple-cn",
    name: {
      en: "TuSimple",
      zh: "图森未来",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.tusimple.com",
    linkedin: "tusimple",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "twosigma-cn",
    name: {
      en: "Two Sigma",
      zh: "Two Sigma",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.twosigma.com",
    linkedin: "two-sigma",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ubisoft-cn",
    name: {
      en: "Ubisoft",
      zh: "育碧",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.ubisoft.com",
    linkedin: "ubisoft",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "unity-cn",
    name: {
      en: "Unity",
      zh: "Unity",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.unity.com",
    linkedin: "unity",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "vipshop-cn",
    name: {
      en: "Vipshop",
      zh: "唯品会",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.vipshop.com",
    linkedin: "vipshop",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "vmware-cn",
    name: {
      en: "VMware",
      zh: "VMware/威睿",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai],
    website: "https://www.vmware.com",
    linkedin: "vmware",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "wework-cn",
    name: {
      en: "WeWork",
      zh: "WeWork",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.wework.com",
    linkedin: "wework",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "wish-cn",
    name: {
      en: "Wish",
      zh: "Wish",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.wish.com",
    linkedin: "wish",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "worksapps-cn",
    name: {
      en: "Works Applications",
      zh: "Works Applications",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.worksapplications.com",
    linkedin: "works-applications",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "xmind-cn",
    name: {
      en: "XMind",
      zh: "XMind",
    },
    region: "CN",
    cities: [C.shenzhen],
    website: "https://www.xmind.com",
    linkedin: "xmind",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "zhihu-cn",
    name: {
      en: "Zhihu",
      zh: "知乎",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.zhihu.com",
    linkedin: "zhihu",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "zoom-cn",
    name: {
      en: "Zoom",
      zh: "Zoom",
    },
    region: "CN",
    cities: [C.hefei, C.hangzhou, C.suzhou],
    website: "https://www.zoom.com",
    linkedin: "zoom",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 25,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "china-life-cn",
    name: {
      en: "China Life",
      zh: "中国人寿",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.guangzhou],
    website: "https://www.chinalife.com",
    linkedin: "china-life",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "samsung-cn",
    name: {
      en: "Samsung Electronics",
      zh: "三星电子",
    },
    region: "CN",
    cities: [C.beijing, C.shanghai, C.shenzhen, C.xian],
    website: "https://www.samsungelectronics.com",
    linkedin: "samsung-electronics",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "dongfeng-nissan-cn",
    name: {
      en: "Dongfeng Nissan",
      zh: "东风日产",
    },
    region: "CN",
    cities: [C.guangzhou, C.wuhan],
    website: "https://www.dongfengnissan.com",
    linkedin: "dongfeng-nissan",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "pg-cn",
    name: {
      en: "Procter & Gamble",
      zh: "宝洁",
    },
    region: "CN",
    cities: [C.shanghai, C.guangzhou],
    website: "https://www.proctergamble.com",
    linkedin: "procter--gamble",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "watsons-cn",
    name: {
      en: "Watsons",
      zh: "屈臣氏",
    },
    region: "CN",
    cities: [C.shanghai, C.guangzhou, C.shenzhen],
    website: "https://www.watsons.com",
    linkedin: "watsons",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "gac-honda-cn",
    name: {
      en: "GAC Honda",
      zh: "广汽本田",
    },
    region: "CN",
    cities: [C.guangzhou],
    website: "https://www.gachonda.com",
    linkedin: "gac-honda",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "kimberly-clark-cn",
    name: {
      en: "Kimberly-Clark",
      zh: "金佰利",
    },
    region: "CN",
    cities: [C.shanghai, C.guangzhou],
    website: "https://www.kimberlyclark.com",
    linkedin: "kimberlyclark",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "colgate-cn",
    name: {
      en: "Colgate",
      zh: "高露洁",
    },
    region: "CN",
    cities: [C.shanghai, C.guangzhou],
    website: "https://www.colgate.com",
    linkedin: "colgate",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "mentholatum-cn",
    name: {
      en: "Mentholatum",
      zh: "曼秀雷敦",
    },
    region: "CN",
    cities: [C.shanghai, C.guangzhou],
    website: "https://www.mentholatum.com",
    linkedin: "mentholatum",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 10,
    },
  },
  {
    id: "mars-cn",
    name: {
      en: "Mars",
      zh: "玛氏",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.mars.com",
    linkedin: "mars",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "general-mills-cn",
    name: {
      en: "General Mills",
      zh: "通用磨坊",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.generalmills.com",
    linkedin: "general-mills",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "astrazeneca-cn",
    name: {
      en: "AstraZeneca",
      zh: "阿斯利康",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.astrazeneca.com",
    linkedin: "astrazeneca",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "firmenich-cn",
    name: {
      en: "Firmenich",
      zh: "Firmenich/芬美意",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.firmenich.com",
    linkedin: "firmenich",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "maersk-cn",
    name: {
      en: "Maersk",
      zh: "马士基",
    },
    region: "CN",
    cities: [C.shanghai, C.shenzhen, C.dalian],
    website: "https://www.maersk.com",
    linkedin: "maersk",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "abb-cn",
    name: {
      en: "ABB",
      zh: "ABB",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen, C.dalian],
    website: "https://www.abb.com",
    linkedin: "abb",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "volvo-cn",
    name: {
      en: "Volvo",
      zh: "沃尔沃",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen, C.dalian],
    website: "https://www.volvo.com",
    linkedin: "volvo",
    params: {
      dailyWorkingHours: 7.5,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 15,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "hexagon-cn",
    name: {
      en: "Hexagon",
      zh: "海克斯康",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.shenzhen],
    website: "https://www.hexagon.com",
    linkedin: "hexagon-ab",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "pfizer-cn",
    name: {
      en: "Pfizer",
      zh: "辉瑞",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.pfizer.com",
    linkedin: "pfizer",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "novartis-cn",
    name: {
      en: "Novartis",
      zh: "诺华",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.novartis.com",
    linkedin: "novartis",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "takeda-cn",
    name: {
      en: "Takeda",
      zh: "武田",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.takeda.com",
    linkedin: "takeda",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ikea-cn",
    name: {
      en: "IKEA",
      zh: "宜家",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.ikea.com",
    linkedin: "ikea",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "loreal-cn",
    name: {
      en: "L'Oréal",
      zh: "欧莱雅",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.loreal.com",
    linkedin: "loreal",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "edrawsoft-cn",
    name: {
      en: "EdrawSoft",
      zh: "亿图图示",
    },
    region: "CN",
    cities: [C.shenzhen],
    website: "https://www.edrawsoft.com",
    linkedin: "edrawsoft",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 1,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 5,
    },
  },
  {
    id: "western-digital-cn",
    name: {
      en: "Western Digital",
      zh: "西部数据",
    },
    region: "CN",
    cities: [C.shanghai, C.shenzhen],
    website: "https://www.westerndigital.com",
    linkedin: "western-digital",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "dolby-cn",
    name: {
      en: "Dolby",
      zh: "杜比",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.dolby.com",
    linkedin: "dolby",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "logitech-cn",
    name: {
      en: "Logitech",
      zh: "罗技",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.logitech.com",
    linkedin: "logitech",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "phoenix-contact-cn",
    name: {
      en: "Phoenix Contact",
      zh: "菲尼克斯电气",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.shenzhen],
    website: "https://www.phoenixcontact.com",
    linkedin: "phoenix-contact",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "rockwell-automation-cn",
    name: {
      en: "Rockwell Automation",
      zh: "罗克韦尔自动化",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.shenzhen],
    website: "https://www.rockwellautomation.com",
    linkedin: "rockwell-automation",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sagemcom-cn",
    name: {
      en: "Sagemcom",
      zh: "萨基姆通讯",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.sagemcom.com",
    linkedin: "sagemcom",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "eli-lilly-cn",
    name: {
      en: "Eli Lilly",
      zh: "礼来",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.lilly.com",
    linkedin: "eli-lilly-and-company",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "johnson-johnson-cn",
    name: {
      en: "Johnson & Johnson",
      zh: "强生",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.jnj.com",
    linkedin: "johnson--johnson",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "henkel-cn",
    name: {
      en: "Henkel",
      zh: "汉高",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.henkel.com",
    linkedin: "henkel",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "basf-cn",
    name: {
      en: "BASF",
      zh: "巴斯夫",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen, C.chengdu],
    website: "https://www.basf.com",
    linkedin: "basf",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "harman-cn",
    name: {
      en: "Harman",
      zh: "哈曼",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.shenzhen, C.chengdu],
    website: "https://www.harman.com",
    linkedin: "harman-international",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "dhl-cn",
    name: {
      en: "DHL",
      zh: "敦豪",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.dhl.com",
    linkedin: "dhl",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "msd-cn",
    name: {
      en: "MSD",
      zh: "默沙东",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.msd.com",
    linkedin: "merck-sharp-and-dohme-corp",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "merck-cn",
    name: {
      en: "Merck",
      zh: "默克",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.merckgroup.com",
    linkedin: "merckgroup",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "desmi-cn",
    name: {
      en: "Desmi",
      zh: "代斯米",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.desmi.com",
    linkedin: "desmi",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "grundfos-cn",
    name: {
      en: "Grundfos",
      zh: "格兰富",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.grundfos.com",
    linkedin: "grundfos",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "atlas-copco-cn",
    name: {
      en: "Atlas Copco",
      zh: "阿特拉斯・科普柯",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.shenzhen],
    website: "https://www.atlascopco.com",
    linkedin: "atlas-copco",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sensirion-cn",
    name: {
      en: "Sensirion",
      zh: "盛思锐",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.sensirion.com",
    linkedin: "sensirion",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "tetra-pak-cn",
    name: {
      en: "Tetra Pak",
      zh: "利乐",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.tetrapak.com",
    linkedin: "tetra-pak",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "pcb-connect-cn",
    name: {
      en: "PCB Connect",
      zh: "PCB Connect",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.pcb-connect.com",
    linkedin: "pcb-connect",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "buhler-cn",
    name: {
      en: "Buhler",
      zh: "布勒",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.buhlergroup.com",
    linkedin: "buhler-group",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "mastercard-cn",
    name: {
      en: "Mastercard",
      zh: "万事达",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.mastercard.com",
    linkedin: "mastercard",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "visa-cn",
    name: {
      en: "Visa",
      zh: "维萨",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.visa.com",
    linkedin: "visa",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "zeiss-cn",
    name: {
      en: "Zeiss",
      zh: "蔡司",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.shenzhen],
    website: "https://www.zeiss.com",
    linkedin: "zeiss",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "thermo-fisher-cn",
    name: {
      en: "Thermo Fisher",
      zh: "赛默飞",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.thermofisher.com",
    linkedin: "thermo-fisher-scientific",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "mettler-toledo-cn",
    name: {
      en: "Mettler Toledo",
      zh: "梅特勒托利多",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.mt.com",
    linkedin: "mettler-toledo",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "olympus-cn",
    name: {
      en: "Olympus",
      zh: "奥林巴斯",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.olympus.com",
    linkedin: "olympus",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "fluke-cn",
    name: {
      en: "Fluke",
      zh: "福禄克",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.fluke.com",
    linkedin: "fluke-corporation",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "juniper-cn",
    name: {
      en: "Juniper Networks",
      zh: "瞻博",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.juniper.net",
    linkedin: "juniper-networks",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "commscope-cn",
    name: {
      en: "CommScope",
      zh: "康普",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.commscope.com",
    linkedin: "commscope",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "jll-cn",
    name: {
      en: "JLL",
      zh: "仲量联行",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.jll.com",
    linkedin: "jll",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "cbre-cn",
    name: {
      en: "CBRE",
      zh: "世邦魏理仕",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.cbre.com",
    linkedin: "cbre",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "stryker-cn",
    name: {
      en: "Stryker",
      zh: "史赛克",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.stryker.com",
    linkedin: "stryker",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "medtronic-cn",
    name: {
      en: "Medtronic",
      zh: "美敦力",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.medtronic.com",
    linkedin: "medtronic",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "karl-storz-cn",
    name: {
      en: "Karl Storz",
      zh: "卡尔史托斯",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.karlstorz.com",
    linkedin: "karl-storz",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "skyscanner-cn",
    name: {
      en: "Skyscanner",
      zh: "天巡",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.skyscanner.com",
    linkedin: "skyscanner",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "zuru-cn",
    name: {
      en: "ZURU",
      zh: "ZURU",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.zuru.com",
    linkedin: "zuru",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "amex-cn",
    name: {
      en: "American Express",
      zh: "美国运通",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.americanexpress.com",
    linkedin: "american-express",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "hasbro-cn",
    name: {
      en: "Hasbro",
      zh: "孩之宝",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.hasbro.com",
    linkedin: "hasbro",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "electrolux-cn",
    name: {
      en: "Electrolux",
      zh: "伊莱克斯",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.electrolux.com",
    linkedin: "electrolux",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "kering-cn",
    name: {
      en: "Kering",
      zh: "开云集团",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.kering.com",
    linkedin: "kering",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "te-connectivity-cn",
    name: {
      en: "TE Connectivity",
      zh: "泰科电子",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.shenzhen],
    website: "https://www.te.com",
    linkedin: "te-connectivity",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "kuehne-nagel-cn",
    name: {
      en: "Kuehne+Nagel",
      zh: "德迅",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.kuehne-nagel.com",
    linkedin: "kuehne-nagel",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "bayer-cn",
    name: {
      en: "Bayer",
      zh: "拜耳",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.bayer.com",
    linkedin: "bayer",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "novo-nordisk-cn",
    name: {
      en: "Novo Nordisk",
      zh: "诺和诺德",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.novonordisk.com",
    linkedin: "novo-nordisk",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "iqvia-cn",
    name: {
      en: "IQVIA",
      zh: "益百利",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.iqvia.com",
    linkedin: "iqvia",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "veeva-cn",
    name: {
      en: "Veeva",
      zh: "Veeva/维沃",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.veeva.com",
    linkedin: "veeva-systems",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "corning-cn",
    name: {
      en: "Corning",
      zh: "康宁",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.corning.com",
    linkedin: "corning-incorporated",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ecocert-cn",
    name: {
      en: "Ecocert",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.ecocert.com",
    linkedin: "ecocert",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "slb-cn",
    name: {
      en: "SLB",
      zh: "斯伦贝谢",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.slb.com",
    linkedin: "slb",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sohu-cn",
    name: {
      en: "Sohu",
      zh: "搜狐",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.sohu.com",
    linkedin: "sohu",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "dxc-cn",
    name: {
      en: "DXC Technology",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.dxc.technology",
    linkedin: "dxc-technology",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "elekta-cn",
    name: {
      en: "Elekta",
      zh: "Elekta/医科达",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.elekta.com",
    linkedin: "elekta",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "ceva-cn",
    name: {
      en: "Ceva",
      zh: "Ceva/诗华",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.ceva.com",
    linkedin: "ceva-logistics",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "cummins-cn",
    name: {
      en: "Cummins",
      zh: "康明斯",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.cummins.com",
    linkedin: "cummins",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "dieffenbacher-cn",
    name: {
      en: "DIEFFENBACHER",
      zh: "迪芬巴赫",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.dieffenbacher.com",
    linkedin: "dieffenbacher",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "bostik-cn",
    name: {
      en: "Bostik",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.bostik.com",
    linkedin: "bostik",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "schaeffler-cn",
    name: {
      en: "Schaeffler",
      zh: "Schaeffler/舍弗勒",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.schaeffler.com",
    linkedin: "schaeffler",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "danone-cn",
    name: {
      en: "Danone",
      zh: "Danone/达能",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.danone.com",
    linkedin: "danone",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "kerry-cn",
    name: {
      en: "Kerry",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.kerrygroup.com",
    linkedin: "kerrygroup",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "beiersdorf-cn",
    name: {
      en: "Beiersdorf",
      zh: "拜尔斯道夫",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.beiersdorf.com",
    linkedin: "beiersdorf",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "organon-cn",
    name: {
      en: "Organon",
      zh: "Organon/欧佳诺",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.organon.com",
    linkedin: "organon",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "lseg-cn",
    name: {
      en: "LSEG",
      zh: "伦敦证券交易所集团",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.lseg.com",
    linkedin: "london-stock-exchange-group",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "wiley-cn",
    name: {
      en: "Wiley",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.wiley.com",
    linkedin: "wiley",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sandvik-cn",
    name: {
      en: "Sandvik",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.home.sandvik",
    linkedin: "sandvik",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "estee-lauder-cn",
    name: {
      en: "Estée Lauder",
      zh: "雅诗兰黛",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.elcompanies.com",
    linkedin: "estee-lauder-companies-inc",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "unilever-cn",
    name: {
      en: "Unilever",
      zh: "联合利华",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou, C.shenzhen],
    website: "https://www.unilever.com",
    linkedin: "unilever",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "jpmorgan-cn",
    name: {
      en: "JPMorgan Chase",
      zh: "摩根大通",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.jpmorganchase.com",
    linkedin: "jpmorgan-chase",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "barclays-cn",
    name: {
      en: "Barclays",
      zh: "巴克莱银行",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.barclays.com",
    linkedin: "barclays",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "agilent-cn",
    name: {
      en: "Agilent",
      zh: "安捷伦",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing, C.guangzhou],
    website: "https://www.agilent.com",
    linkedin: "agilent-technologies",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "alten-cn",
    name: {
      en: "ALTEN",
      zh: "ALTEN/奥尔腾",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.alten.com",
    linkedin: "alten",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "bv-cn",
    name: {
      en: "Bureau Veritas",
      zh: "必维国际检验集团",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.bureauveritas.com",
    linkedin: "bureau-veritas",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "bruker-cn",
    name: {
      en: "Bruker",
      zh: "Bruker/布鲁克",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.bruker.com",
    linkedin: "bruker",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sartorius-cn",
    name: {
      en: "Sartorius",
      zh: "Sartorius/赛多利斯",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.sartorius.com",
    linkedin: "sartorius",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "nikon-cn",
    name: {
      en: "Nikon",
      zh: "尼康",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.nikon.com.cn",
    linkedin: "nikon-corporation",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "reuters-cn",
    name: {
      en: "Reuters",
      zh: "路透社",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.reuters.com",
    linkedin: "reuters",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "cambridge-university-press-cn",
    name: {
      en: "Cambridge University Press",
      zh: "剑桥大学出版社",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.cambridge.org",
    linkedin: "cambridge-university-press",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "nomura-cn",
    name: {
      en: "Nomura",
      zh: "野村证券",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.nomura.com",
    linkedin: "nomura",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "zhuoshi-cn",
    name: {
      en: "Zhuoshi Quantitative",
      zh: "卓识量化",
    },
    region: "CN",
    cities: [C.shanghai],
    website: "https://www.zhuoshiquant.com",
    linkedin: "zhuoshi-quantitative-investment",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "anz-cn",
    name: {
      en: "ANZ",
      zh: "澳新银行",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.anz.com",
    linkedin: "anz",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "thales-ca",
    name: {
      en: "Thales",
      zh: "泰雷兹",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.thalesgroup.com",
    linkedin: "thalesgroup",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "dh-cn",
    name: {
      en: "Donghua Software",
      zh: "东华软件",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.dhcc.com.cn",
    linkedin: "donghua-software-co-ltd",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "aerospace-cn",
    name: {
      en: "Aerospace Information",
      zh: "航天信息",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.aisino.com",
    linkedin: "aisino",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "topsec-cn",
    name: {
      en: "Topsec",
      zh: "天融信",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.topsec.com.cn",
    linkedin: "topsec",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "jiyi-cn",
    name: {
      en: "Jiyi Network",
      zh: "极意网络",
    },
    region: "CN",
    cities: [C.beijing],
    website: "https://www.jiyi.com",
    linkedin: "jiyi-network",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 20,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "obel-cn",
    name: {
      en: "Obel",
      zh: "欧倍尔",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.obel.com.cn",
    linkedin: "obel",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "huayu-cn",
    name: {
      en: "Huayu Software",
      zh: "华宇软件",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.huayu.com.cn",
    linkedin: "huayu-software",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "seeyon-cn",
    name: {
      en: "Seeyon",
      zh: "致远互联",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.seeyon.com",
    linkedin: "seeyon",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "sifang-cn",
    name: {
      en: "Sifang Automation",
      zh: "四方继保",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.sifang.com.cn",
    linkedin: "sifang-automation",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 15,
    },
  },
  // 长亭科技
  {
    id: "ctsecurity-cn",
    name: {
      en: "CTSecurity",
      zh: "长亭科技",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.ctsecurity.com.cn",
    linkedin: "ctsecurity",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 15,
    },
  },
  {
    id: "lenovo-cn",
    name: {
      en: "Lenovo",
      zh: "联想集团",
    },
    region: "CN",
    cities: [C.shanghai, C.beijing],
    website: "https://www.lenovo.com",
    linkedin: "lenovo",
    params: {
      dailyWorkingHours: 8,
      dailyCommuteHours: 1,
      dailyCommunicationOutsideWorkHours: 0.5,
      weeklyWorkingDays: 5,
      annualPaidLeaveDays: 10,
      annualPaidSickLeaveDays: 15,
    },
  },
];
